update: # Updater courtesy of inventivetalent
  # If you want the plugin to notify you of any updates.
  check: true
  # If you want the plugin to automatically download the new version. The new version will activate upon server restart. The above must be true.
  download: false
modify:
  # Added to try to provide functionality with the Shopkeepers plugin. Set to false if you do not want this plugin to modify villager inventories.
  villagers: true
command:
  permission: ah.reload
  reloaded: '&6The AttributeHider configuration has been reloaded.'
  no-permission: '&6You do not have permission to use this command!'
lists: # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html - This is the list of all available materials, CASE_SENSITIVE.
  attributes: # The below options are only for attributes.
     # If true, adds the below list to what the plugin already modifies. If false, only modifies the below list, ignoring what the plugin already modifies.
    mode: true
    list: # List of item ids to remove attributes on. If you're happy with what the plugin already modifies, you don't have to change anything.
    - 'EXAMPLE_ID'
  enchants: # List of item ids to hide enchantments on. To disable, remove all values except the first one then change the first value to 'EXAMPLE_ID'.
  - 'EXAMPLE_ID'
# Don't touch this
version: 2