# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html - This is the list of all available materials, CASE_SENSITIVE.
# You can change the lists to true or false, one material, or a list of materials.
# True means it will remove the modifier from all items. False means it will not remove the modifier from any item.
# Explicitly putting a material/some materials will whitelist only those materials to be modified.
# Here's an example of possible values:
#
# lists:
#   attributes: DIAMOND_SWORD # Hides attributes for a diamond sword only.
# -- or --
# lists:
#   enchants: # Hides enchants for a diamond sword and a diamond axe only.
#   - DIAMOND_SWORD
#   - DIAMOND_AXE
# -- or --
# lists:
#   potions: false # Will not hide any potion effects for any item.
# -- or --
# lists:
#   unbreakable: true # Hides the unbreakable tag on all items.
#

lists:
  attributes: true
  enchants: false
  potions: false
  unbreakable: false
command:
  permission: ah.reload
  reloaded: '&6The AttributeHider configuration has been reloaded.'
  no-permission: '&6You do not have permission to use this command!'
check-updates: true
