name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 4.1.0
depend: [ProtocolLib]
commands:
  attributehider:
    usage: /ah reload
    description: Reloads the AttributeHider configuration.
    aliases: [ah]