name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 5.6.1
description: Hides selected item attributes.
author: Kabryxis
depend: [ProtocolLib]
softdepend: [Shopkeepers]
api-version: 1.15
commands:
  attributehider:
    usage: /ah reload
    description: Reloads the AttributeHider configuration.
    aliases: [ah]
