name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 6.1.0
api-version: '1.13'
description: Hides select item attributes.
author: Warren1001
depend: [ProtocolLib]
commands:
  attributehider:
    usage: /ah
    description: Reloads the AttributeHider configuration.
    aliases: [ah]
