name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 6.0.0
api-version: '1.16'
description: Hides select item attributes.
author: Kabryxis/Warren1001
depend: [ProtocolLib]
commands:
  attributehider:
    usage: /ah
    description: Reloads the AttributeHider configuration.
    aliases: [ah]
