name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 5.0.0
depend: [ProtocolLib]
softdepend: [Shopkeepers]
commands:
  attributehider:
    usage: /ah reload
    description: Reloads the AttributeHider configuration.
    aliases: [ah]