name: AttributeHider
main: com.kabryxis.attributehider.AttributeHider
version: 5.1.1
description: Hides selected item attributes.
author: Kabryxis
depend: [ProtocolLib]
softdepend: [Shopkeepers]
commands:
  attributehider:
    usage: /ah reload
    description: Reloads the AttributeHider configuration.
    aliases: [ah]